@php
    $navigationLinks = [
        ['label' => 'Features', 'href' => '#features'],
        ['label' => 'How It Works', 'href' => '#how-it-works'],
        ['label' => 'Pricing', 'href' => '#pricing'],
    ];

    $features = [
        ['title' => 'Deep Content Analysis', 'description' => 'Analyze writing patterns, vocabulary choices, and sentence structure to detect AI-generated content with precision.'],
        ['title' => 'Passage Highlighting', 'description' => 'Pinpoint exactly which sentences or phrases triggered detection with clear visual emphasis.'],
        ['title' => 'Smart Rewriting', 'description' => 'Rewrite flagged passages in a more natural tone while preserving your intended meaning.'],
        ['title' => 'Confidence Scoring', 'description' => 'Review per-sentence confidence levels and overall AI probability at a glance.'],
        ['title' => 'Secure & Private', 'description' => 'Your analysis data is encrypted and never used to train external models.'],
        ['title' => 'Instant Results', 'description' => 'Get comprehensive analysis in seconds with no complex setup.'],
    ];

    $steps = [
        ['number' => '01', 'title' => 'Paste Your Text', 'description' => 'Drop in any piece of writing: essay, article, email, or social copy.'],
        ['number' => '02', 'title' => 'Get Instant Analysis', 'description' => 'Nuance scans each sentence and highlights passages most likely generated by AI.'],
        ['number' => '03', 'title' => 'Rewrite & Refine', 'description' => 'Apply rewrite guidance to produce natural, confident, and authentic copy.'],
    ];

    $plans = [
        ['name' => 'Free', 'price' => '$0', 'period' => 'forever', 'description' => 'Perfect for trying it out', 'featured' => false, 'features' => ['5 analyses per day', 'Basic highlighting', 'Up to 1,000 words', 'Standard accuracy']],
        ['name' => 'Pro', 'price' => '$12', 'period' => 'per month', 'description' => 'For writers who mean business', 'featured' => true, 'features' => ['Unlimited analyses', 'Advanced highlighting', 'Up to 10,000 words', 'Premium accuracy', 'Smart rewriting', 'Writing sample matching']],
        ['name' => 'Team', 'price' => '$39', 'period' => 'per month', 'description' => 'For editorial teams & agencies', 'featured' => false, 'features' => ['Everything in Pro', '5 team members', 'API access', 'Bulk analysis', 'Priority support', 'Custom integrations']],
    ];
@endphp

<div>
    <x-marketing.header :links="$navigationLinks" />

    <main>
        <x-marketing.hero-section />
        <x-marketing.features-section :features="$features" />
        <x-marketing.how-it-works-section :steps="$steps" />
        <x-marketing.pricing-section :plans="$plans" />
        <x-marketing.cta-section />
    </main>

    <x-marketing.footer :product-links="$navigationLinks" />
</div>
